export const branchActionTypes = {
  SET_BRANCHES_LIST: 'SET_BRANCHES_LIST',
  SET_CURRENT_BRANCH: 'SET_CURRENT_BRANCH',
  SET_CURRENT_QUESTION_ID: 'SET_CURRENT_QUESTION_ID',
  ADD_ANSWER: 'ADD_ANSWER',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  SET_ANSWERS_COLLECTED: 'SET_ANSWERS_COLLECTED',
  CLEAR_ANSWERS: 'CLEAR_ANSWERS'
}
